CONFIG=$PWD/scripts/config

#Basic DEBUG options
$CONFIG --enable CONFIG_DEBUG_OBJECTS
$CONFIG --enable CONFIG_DEBUG_OBJECTS_FREE
$CONFIG --enable CONFIG_DEBUG_OBJECTS_TIMERS
$CONFIG --enable CONFIG_DEBUG_OBJECTS_WORK
$CONFIG --enable CONFIG_DEBUG_OBJECTS_PERCPU_COUNTER
$CONFIG --set-val CONFIG_DEBUG_OBJECTS_ENABLE_DEFAULT 1
$CONFIG --enable CONFIG_DEBUG_SLAB
$CONFIG --enable CONFIG_DEBUG_SLAB_LEAK
$CONFIG --enable CONFIG_STACK_USAGE


#LOOKUP and HANGS
$CONFIG --enable CONFIG_LOCKUP_DETECTOR
$CONFIG --disable CONFIG_DETECT_HUNG_TASK
$CONFIG --disable CONFIG_PANIC_ON_OOPS
$CONFIG --enable CONFIG_KALLSYMS

#LOCKs
$CONFIG --enable CONFIG_DEBUG_SPINLOCK
$CONFIG --enable CONFIG_DEBUG_MUTEXES
$CONFIG --enable CONFIG_DEBUG_ATOMIC_SLEEP

#LIST
$CONFIG --enable CONFIG_DEBUG_LIST

#Basic Network options

#RCU debug options
$CONFIG --enable CONFIG_SPARSE_RCU_POINTER
$CONFIG --enable CONFIG_DEBUG_OBJECTS
$CONFIG --enable CONFIG_PROVE_RCU
$CONFIG --enable CONFIG_DEBUG_OBJECTS_RCU_HEAD

#Compile in default drivers used by openvswitch
$CONFIG --enable CONFIG_VXLAN
$CONFIG --enable CONFIG_GRE
$CONFIG --enable CONFIG_LIBCRC32C

#Turn all '=m' into '=y'
sed s/\=m$/=y/ .config >.config_sed
mv .config_sed .config

